### ISSUE TITLE
Float32 volume shader

### ISSUE THREAD

**Issue by jtristano** [Twinklebear/webgl-marching-cubes#3]
Hi Will,
I successfully update the code to use float32 as the marching cubes input but I cannot update the volumeshader to take R32F input as seen here

I'm checking fp textures in the browser as well

```
	const ext = gl.getExtension('EXT_color_buffer_float');
	if (!ext) {
		console.log('Your browser does not support floating point textures');
		setHudText("Your browser does not support floating point textures");
		return;
	}
```

```
	var tex = gl.createTexture();
	gl.activeTexture(gl.TEXTURE0);
	gl.bindTexture(gl.TEXTURE_3D, tex);
	gl.texStorage3D(gl.TEXTURE_3D, 1, gl.R32F, volDims[0], volDims[1], volDims[2]);
	gl.texParameteri(gl.TEXTURE_3D, gl.TEXTURE_MIN_FILTER, gl.LINEAR);
	gl.texParameteri(gl.TEXTURE_3D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
	gl.texParameteri(gl.TEXTURE_3D, gl.TEXTURE_WRAP_R, gl.CLAMP_TO_EDGE);
	gl.texParameteri(gl.TEXTURE_3D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
	gl.texParameteri(gl.TEXTURE_3D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
	gl.texSubImage3D(gl.TEXTURE_3D, 0, 0, 0, 0,
		volDims[0], volDims[1], volDims[2],
		gl.RED, gl.FLOAT, dataBuffer);
```

data buffer conversion

```
			var dataBufferU = new Uint8Array(respBuf);
			//sum databufferu and print it
			console.log(dataBufferU.reduce((a, b) => a + b, 0));
			dataBuffer = new Float32Array(dataBufferU.length);
			// divide every element by 255.0
			for (var i = 0; i < dataBuffer.length; i++) {
				dataBuffer[i] = dataBufferU[i]/255.0;
				if (dataBuffer[i] > 1.0) {
					dataBuffer[i] = 1.0;
				}
				else if (dataBuffer[i] < 0.0) {
					dataBuffer[i] = 0.0;
				}
			}
			console.log(dataBuffer.reduce((a, b) => a + b, 0));
```

Thanks!
Joe

**Comment by Twinklebear** [comment]
Hi Joe, the setup here looks right, but I think what may be wrong is the extension you need to enable. I think `EXT_color_buffer_float` is just for making float textures renderable, but because you want linear texture filtering on float textures you should enable `OES_texture_float_linear`: https://registry.khronos.org/webgl/extensions/OES_texture_float_linear/ . It looks to have pretty broad support: https://web3dsurvey.com/webgl2/extensions/OES_texture_float_linear . If you switch to nearest interpolation I think you should see something show up as a sanity check as well, and with that extension linear interpolation should be supported.

Let me know if that gets it running

**Comment by jtristano** [comment]
That extension did the trick! Thanks!
